const slider = 
[
    {
    img:"./img/collection-img-1.jpg",
    lastName:"Doe",
  
},
{
    img:"./img/collection-img-2.jpg",
    lastName:"Doe", 
},
{
    img:"./img/collection-img-3.jpg",
    lastName:"Doe", 
},
{
    img:"./img/collection-img-4.jpg",
    lastName:"Doe", 
},
{
    img:"./img/team-img-1.jpg",
    lastName:"Doe", 
},
{
    img:"./img/team-img-2.jpg",
    lastName:"Doe", 
},
{
    img:"./img/team-img-3.jpg",
    lastName:"Doe", 
},
{
    img:"./img/team-img-4.jpg",
    lastName:"Doe", 
},
{
    img:"./img/team-img-5.jpg",
    lastName:"Doe", 
},
{
    img:"./img/team-img-6.jpg",
    lastName:"Doe", 
},
{
    img:"./img/team-img-7.jpg",
    lastName:"Doe", 
},
{
    img:"./img/team-img-8.jpg",
    lastName:"Doe", 
}
]
;
export default slider;